name: Cerver Code Coverage

on:
  pull_request:
    branches:
      - '*'

jobs:
  coverage:
    name: Cerver coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      # compile
      - name: gcc make
        run: make TYPE=test
      - name: gcc tests
        run: make TYPE=test test

      # run
      - name: test
        run: bash test/run.sh

      - name: coverage
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          name: build
          fail_ci_if_error: true
          # verbose: true

      - name: clear
        run: make clear

      - name: g++ tests
        run: make TYPE=test CC=g++ test
      - name: g++ run tests
        run: bash test/run.sh