name: Cerver Pre-Release

on:
  push:
    branches:
      - '*beta'

jobs:
  build:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version file
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Read changelog
        id: get_changes
        run: |
          changes=$(cat CHANGELOG.md)
          changes="${changes//'%'/'%25'}"
          changes="${changes//$'\n'/'%0A'}"
          changes="${changes//$'\r'/'%0D'}"
          echo "::set-output name=changes::$changes"

      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: HTTP Beta ${{ steps.get_version.outputs.version }}
          body: ${{ steps.get_changes.outputs.changes }}
          draft: false
          prerelease: true